### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by xYosemite** [AlexSterk/TwitchDropGrabber#19]
Hi there, I am quite interested in this repository however use a laptop that isn't online 24/7. I am wondering how I would go about, instead, installing this script on my Linux/Ubuntu VPS and just have it run 24/7? Since it needs a running Chrome.exe--I figured Puppeteer could just come with that for Linux but have no idea removing the need for the exe.

Thanks in advance.

**Comment by AlexSterk** [comment]
Unfortunately, you need Google Chrome specifically. Chromium will not work since it lacks support for most video/audio formats, which are used by Twitch.

Since you are using Ubuntu, maybe you can try some guides on installing Google Chrome: I found this one https://askubuntu.com/questions/245041/how-do-i-install-chrome-on-a-server but there could be others

It doesn't have to be a .exe file specifically, as long as it's the entry point to the Chrome application
